eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka

spring:
  data:
    mongodb:
      database: orderdb
      uri: mongodb+srv://admin:Canada001@order-service-cluster.tvhfvhp.mongodb.net/?retryWrites=true&w=majority
      port: 27017
      host: order-service-cluster.tvhfvhp.mongodb.net
      repositories:
        type: auto


