eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantDB
#    url: jdbc:mysql://mysql-db-instance.chqlhhmbfegs.us-east-1.rds.amazonaws.com:3306/restaurantDB
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
      show-sql: true